# Generated by Django 5.2 on 2025-05-08 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_store_manager_supplier_stores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
